### PR TITLE
Added start of claims support

### LINKED ISSUE #63: Claiming land implementation
A lot of people like the option of claiming there precious builds or loot, but hate the faction side of things, by not having the ability to raid claimed land, I think the implementation of claims would take this plug-in to the next level, inviting someone to your team you also trust them to be part of your claim, a really cool idea would be to make it so that players must put items in a chest (diamonds, iron, gold) or even items of choosing in config to maintain the claimed land, the more land they claim the more ores are used and the less time they will have, this gives a player a reason to login and grind everyday to keep there claim stable and safe from other players this also means that when players become inactive your not left with claimed land everywhere, here’s an example of the plug-in that I think would be a great inspiration (ultimateClaims) link:  https://songoda.com/marketplace/product/ultimateclaims-the-ultimate-claiming-plugin.65

### PR DESCRIPTION
**Pull request by booksaw**
TODO: 
- [x] Add config option to disable the integration 
- [x] Fix problem where added members do not persist across reloads
- [x] Name the claim the teams name
- [x] Cancel transferOwnership event (I have requested this be added to the other plugin) unless the player is a team owner (else the plugin will get confused)

closes #63

### CODE REVIEW

**Comment by Gontijo8199** [comment]
How would that work @booksaw ? The claiming system...

**Comment by booksaw** [comment]
> How would that work @booksaw ? The claiming system...

Claims will be associated with teams instead of players. 
All members of a team will be trusted in the claim. 
The owner of the team can manually trust other players outside of their team.

**Comment by Gontijo8199** [comment]
It would be cool if you could buy claims with team points or if you invite new players to your team!

**Comment by booksaw** [comment]
I had not thought of adding team score as a possible currency to keep the claim alive.
I will look into doing this, but I think it may have to be done by ultimateClaims instead of by me

**Pull request merged**
