### PR TITLE
Replacing List with Set.

### PR DESCRIPTION
**Pull request by svaningelgem**
I noticed that a lot of Lists were used for allies and chests etc, but it didn't really matter what order this was in. Just that it was available.

I changed this now to use `Set`'s which should improve the performance a little bit.
Plus-side: it didn't need much refactoring.

FYI difference in timings:
``` 
ArrayList add: 3.823 ms
HashSet add: 3.026 ms
ArrayList contains: 1.756.988 ms
HashSet contains: 3.222 ms
ArrayList remove: 168.611 ms
HashSet remove: 4.121 ms
```

The addition is quite similar in performance, but the check and removal are much, much faster.

Please let me know if you would need some adjustments here.

### CODE REVIEW

**Review by booksaw — APPROVED** [review]
Thanks :)

**Comment by booksaw** [comment]
That is a lot of merge conflicts, this could be fun

**Comment by svaningelgem** [comment]
ow cr*p. I'll have a look.

**Comment by booksaw** [comment]
Most were just import conflicts, don't worry I've sorted them, and ill just do an additional commit to add a couple of things that had missing functionality

**Pull request merged**
