### PR TITLE
Enhances /teama teleport

### LINKED ISSUE #534: [FEATURE] /teama home all
### What is the feature request for?

Create an admin /teama home all command to teleport all teams to all their homes

### Relevant links

_No response_

### Additional Information

_No response_

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

### PR DESCRIPTION
**Pull request by EarthCow**
Reworks the /teama teleport command adding a bunch of new features. Teleporting all teams at once is now possible as well as teleporting teams to their homes (closes #534). Additionally, an optional argument was added to allow the specification of a world.

The command can now also be run by the console as long as when teleporting to a location a world is specified.

The new commands are as follows:

|Command|Usage|
|--------|--------|
| /teama teleport team \<team\>| Teleports the team to the command issuer's location. Must be run by a player |
| /teama teleport team \<team\> home| Teleports the team to their team home if they have one|
| /teama teleport team \<team\> location \<x\> \<y\> \<z\> [yaw\|world] [pitch] [world]| Teleports the team to the location. If using from console the world argument is required|
| /teama teleport team \<team\> player \<player\> | Teleports the team to the specified player|
| /teama teleport all| Teleports all teams to the issuer's location. Must be run by a player| 
| /teama teleport all home| Teleports all teams to their team home if they have one| 
| /teama teleport all location \<x\> \<y\> \<z\> [yaw\|world] [pitch] [world]| Teleports all teams to the location. If using from console the world argument is required| 
| /teama teleport all player \<player\>| Teleports all teams to the specified player|

### CODE REVIEW

**Review by booksaw — CHANGES_REQUESTED** [review]
This is a really good change, (I know it will be a lot of work so I'm happy to help out if you don't have the time) but could this be changed to be a little more user friendly by making the commands a little longer?
Adding commands something like 
* /teama teleport team <team> location <x> <y> <z> [pitch] [yaw] [world] - Teleport the team to the given location 
* /teama teleport team <team> home - teleports all players to their home
* /teama teleport all location <x> <y> <z> - Teleport all teams to that location (I'm not relaly sure why this would ever be used, but good just to cover all bases)
* /teama teleport all home - Teleport all teams to their home

If you are able to / have a better suggestion let me know.
I will have a think about how this could be best reflected within the in-game help messages (I would imagine it would be something along the lines of only listing /teama teleport within the main help message, then having a custom sub-message)

I would suggest you also try and separate the code a little bit to make it more maintainable.
Such as using helper methods to make it a little less complex so you can do something like this:
```java
List<Team> team = getTargetTeams(args[0]);
HashMap<Team, Location> teleports = getTargetLocations(args);
teleportTeams(teleports);
```
Or something a bit different, just thinking off the top of my head.

**Comment by EarthCow** [comment]
Thanks for the review and the suggested changes. I agree that would be much better. I'll look into it when I have time, maybe tonight.

**Comment by EarthCow** [comment]
Just to make sure we're on the same page would the commands we're adding look like this?
- /teama teleport team \<team\> home
- /teama teleport team \<team\> location \<x\> \<y\> \<z\> [yaw] [pitch] [world]
- /teama teleport team \<team\> player <player>
- /teama teleport all home
- /teama teleport all location \<x\> \<y\> \<z\> [yaw] [pitch] [world]
- /teama teleport all player \<player\>

**Comment by booksaw** [comment]
Yeah that looks good, if you can think of something that is better then please go ahead with it, I'm just not a big fan of the ":all" notation as I think that may confuse less experienced users as its not something that is common in other plugins.

**Comment by EarthCow** [comment]
Yeah I understand. I reworked the code and added the subcommands. It is still somewhat complex and I don't know what to do about the argument list. I may revisit the tab completion method to try and clarify the code, however this is a working implementation. You'll have to let me know what you think.

**Comment by EarthCow** [comment]
I also added console support with the requirement of a specified world in that commit (6d1675e).

**Comment by dleovl** [comment]
cool pr i need this so badly

**Review by booksaw — APPROVED** [review]
I really like how you have organized the code, thank you for adding this. Even this week someone was asking on the discord how to teleport teams with one of the functions added in this PR.

**Comment by EarthCow** [comment]
Thank you. I'm glad you like it and it's good to know users will find it useful.

**Comment by dleovl** [comment]
This helps me and my grandmother play

**Pull request merged**
