### PR TITLE
Improve placeholder system

### PR DESCRIPTION
**Pull request by booksaw**
Aims to standardize the placeholder process, by using the same placeholder system for both player based placeholders (such as %betterteams_name%) along with ranked placeholders (such as &betterteams_position_1_name%). 
This PR ensures all types of placeholder, such as relational, ranked etc. have the exact same suffixes (such as name, money etc.) 

Some previous placeholders will need to be re-made with the new syntax.

Invalidates the following PRs due to implementing their changes in the reworked system: #474 #470. These contributions are still greatly appreciated as they were the starting point of this rewrite.

Due to including the requested features in the following feature requests, this PR closes: #463 #451 #473 #442 #438 #389 #343 #399

### CODE REVIEW

**Comment by booksaw** [comment]
@SavageAvocado @Aeliios As you have worked with this plugins placeholders code, I would appreciate any feedback on this PR.

**Comment by SavageAvocado** [comment]
Looks great! There's just one small thing I noticed, It looks like you missed a System.out.println in the DescriptionPlaceholderProvider.

**Comment by Aeliios** [comment]
Hey, I've made multiple suggestions on your code (wrong array input & npe fix), otherwise it looks great.

**Comment by booksaw** [comment]
> Hey, I've made multiple suggestions on your code (wrong array input & npe fix), otherwise it looks great.

Hey, I cant find your proposed changes, please could you let me know where to find them

**Review by Aeliios — CHANGES_REQUESTED** [review]

**Pull request merged**
